/*
 * barectf_tracing.c
 *
 * Copyright (c) 2014 Philippe Proulx <philippe.proulx@efficios.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program, see the file COPYING.  If not, see
 * <http://www.gnu.org/licenses/>.
 */

/*
 * This is the host side of the barectf tracing example.
 *
 * The program allocates 16 buffers of 512 bytes in shared memory, then
 * loads and launches the device program on all 16 cores. The 16 cores,
 * once synchronized, do some computation and write plain CTF to their
 * local packet buffer thanks to C code generated by barectf. At the
 * end, they copy their local buffer to a specific shared memory buffer
 * and enter an idle state.
 *
 * The host program (this program), which waited a few seconds for all
 * cores to finish their jobs, reads back those 16 shared buffers and
 * outputs them as is to 16 files named "stream_<id>", where <id> is
 * the core ID. Those 16 files, along with the original CTF metadata
 * file which was used by barectf to generate C code, forms a complete
 * CTF trace which may be read by Babeltrace.
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <e-hal.h>

#define SHARED_BUF_SIZE		512
#define SHARED_BUF_OFFSET	0x01000000

int main(void)
{
	/* initialize HAL, reset the whole system and get platform infos */
	e_platform_t platform;

	e_init(NULL);
	e_reset_system();
	e_get_platform_info(&platform);

	/* initialize 16 buffers in shared memory */
	e_mem_t emem[16];
	size_t i;

	for (i = 0; i < 16; ++i) {
		e_alloc(&emem[i], SHARED_BUF_OFFSET + i * SHARED_BUF_SIZE,
			SHARED_BUF_SIZE);
	}

	/*
	 * Initialize 16 devices, reset them and load and launch device
	 * program.
	 */
	e_epiphany_t dev[16];

	for (i = 0; i < 16; ++i) {
		e_open(&dev[i], i % 4, i / 4, 1, 1);
		e_reset_group(&dev[i]);
		printf("loading and starting program of core %u\n", i);
		e_load("e_barectf_tracing.srec", &dev[i], 0, 0, E_TRUE);
	}

	/* wait for all 16 cores to finish their job */
	puts("waiting cores to finish their job");
	sleep(4);

	/* read back CTF packets stored in shared memory by cores */
	char packets[16][SHARED_BUF_SIZE];

	for (i = 0; i < 16; ++i) {
		e_read(&emem[i], 0, 0, 0, &packets[i], SHARED_BUF_SIZE);
	}

	/* write CTF packets to files without changes */
	for (i = 0; i < 16; ++i) {
		char buf[32];

		sprintf(buf, "../ctf/stream_%u", i);

		FILE* fh = fopen(buf, "wb");

		char* corepacket = packets[i];

		fwrite(corepacket, 1, SHARED_BUF_SIZE, fh);
		fclose(fh);

		/* close the device now */
		e_close(&dev[i]);
	}

	/* free shared memory blocks */
	for (i = 0; i < 16; ++i) {
		e_free(&emem[i]);
	}

	/* finalize HAL */
	e_finalize();
	puts("done!");

	return 0;
}
